# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250206-202517-dull-pole

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# pipeline:
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 2
#     max_ngram: 4
#   - name: DIETClassifier
#     intent_ranking_length: 3
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     se_masked_language_model: true
#     intent_classification: true
#     entity_recognition: true
#     use_multi_intents: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1
#   - name: custom_components.bert_intent_classifier.BertIntentClassifier 
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 4
  - name: DIETClassifier
    intent_ranking_length: 5
    epochs: 100
    constrain_similarities: true
  - name: custom_components.bert_intent_classifier.BertIntentClassifier 
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: True
    use_masked_language_model: False  
    intent_classification: True
    entity_recognition: True
    use_multi_intents: True
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.2

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    constrain_similarities: true
